services:
  app:
    image: iw-incubator:latest
    container_name: iw-incubator
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - BASEURI=/
      # PostgreSQL configuration
      - PG_URL=jdbc:postgresql://postgres:5432/incubator
      - PG_USERNAME=incubator
      - PG_PASSWORD=${POSTGRES_PASSWORD:-development}

      # FIO Bank configuration (under 'fio' prefix in ZIO Config)
      - FIO_ENCRYPTIONKEY=${FIO_ENCRYPTIONKEY}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    container_name: iw-incubator-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=incubator
      - POSTGRES_USER=incubator
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-development}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U incubator"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    name: iw-incubator-postgres-data
